# Generated by Django 5.1.3 on 2024-11-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expected_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('real_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline', models.DateField()),
                ('pay_date', models.DateField()),
                ('category', models.CharField(choices=[('RENT', 'Rent/Mortgage'), ('UTIL', 'Utilities'), ('FOOD', 'Groceries/Food'), ('TRANS', 'Transportation'), ('MED', 'Medical/Healthcare'), ('INS', 'Insurance'), ('ENT', 'Entertainment'), ('EDU', 'Education'), ('SAV', 'Savings/Investment'), ('OTH', 'Other Expenses')], max_length=10)),
            ],
        ),
    ]
