# Generated by Django 5.1.3 on 2024-11-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDraftList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Draft List', help_text='Name of the draft list', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month (e.g., January, February)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2024')),
                ('name', models.CharField(blank=True, editable=False, help_text="Generated automatically as 'Month Year'", max_length=255)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='real_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expected_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline', models.DateField()),
                ('pay_date', models.DateField()),
                ('category', models.CharField(choices=[('RENT', 'Rent/Mortgage'), ('UTIL', 'Utilities'), ('FOOD', 'Groceries/Food'), ('TRANS', 'Transportation'), ('MED', 'Medical/Healthcare'), ('INS', 'Insurance'), ('ENT', 'Entertainment'), ('EDU', 'Education'), ('SAV', 'Savings/Investment'), ('OTH', 'Other Expenses')], max_length=10)),
                ('draft_list', models.ForeignKey(help_text='The draft list this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='expenses.expensedraftlist')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_list',
            field=models.ForeignKey(default=1, help_text='The list this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.expenselist'),
            preserve_default=False,
        ),
    ]
