# Generated by Django 5.1.3 on 2024-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensedraftlist_expenselist_alter_expense_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedraft',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensedraft',
            name='expected_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='expensedraft',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
