# Generated by Django 5.1.3 on 2024-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensedraft_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedraftlist',
            name='name',
            field=models.CharField(default='Default Draft List', help_text='Name of the draft list', max_length=255, unique=True),
        ),
    ]
